version: '3.1'
services:
  nodejs-basic-shop-web:
    image: nodejs-basic-shop-web
    # build: .
    container_name: nodejs-basic-shop-web
    networks:
      - internal_network
    ports:
      - 80:80

    volumes:
      - ./views:/app/views/
      - ./public:/app/public/

networks:
  internal_network:
    driver: bridge

# build images files 
# docker build -t nodejs-basic-shop-web .
# docker-compose up

# docker build --no-cache -t nodejs-basic-shop-web .